### PR TITLE
[PR 16039] ios Darwin_embedded build change

### PR DESCRIPTION
**Pull request by fuzzard**
https://github.com/xbmc/xbmc/pull/16039

Merged if/when the above PR is merged into kodi master

### CODE REVIEW

**Comment by Rechi** [comment]
Master branch is no longer used, current active branch is Leia.

**Comment by fuzzard** [comment]
I assume you don't want this pushed to a Leia branch though, obviously not backwards compatible with Leia.
I can either do an if darwin_embedded or iOS if you need, what is the preference?

**Comment by Rechi** [comment]
Yes, if darwin_embedded or ios is what I had in mind.

**Comment by fuzzard** [comment]
No problems,  I'll update all the ones next week when I get some time

**Pull request closed without merging**
